--- pyproject.toml.orig	2025-03-09 07:53:59.000000000 -0400
+++ pyproject.toml	2025-12-26 10:38:23.072808000 -0500
@@ -1,5 +1,5 @@
 [build-system]
-requires = ["setuptools>=64.0", "wheel>=0.37.1"]
+requires = ["setuptools>=62.0", "wheel>=0.37.1"]
 build-backend = "setuptools.build_meta"
 
 [project]
